# Generated by Django 5.1.4 on 2024-12-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs')], max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('country_of_passport', models.CharField(max_length=100)),
                ('landline_number', models.CharField(max_length=15)),
                ('company_address', models.TextField()),
                ('company_city', models.CharField(max_length=100)),
                ('company_state', models.CharField(blank=True, max_length=100, null=True)),
                ('company_postal_code', models.CharField(max_length=10)),
                ('company_country', models.CharField(max_length=100)),
                ('agree_terms', models.BooleanField(default=False)),
                ('over_18', models.BooleanField(default=False)),
            ],
        ),
    ]
