# Generated by Django 5.1.4 on 2024-12-11 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_remove_userprofile_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the currency (e.g., US Dollar, Indian Rupee).', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the tour category.', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the tour type (e.g., India, International).', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type of the tour (e.g., Fixed Departures, Fixed Departures with Airfares, etc.).', max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=uuid.uuid4, help_text='Unique code for the tour.', max_length=50, unique=True)),
                ('short_description', models.CharField(help_text='Short title or description of the tour.', max_length=255)),
                ('long_description', models.TextField(help_text='Detailed description of the tour.')),
                ('number_of_nights', models.PositiveIntegerField(help_text='Number of nights for the tour.')),
                ('number_of_days', models.PositiveIntegerField(help_text='Number of days for the tour.')),
                ('departure_city', models.CharField(help_text='City of departure.', max_length=100)),
                ('feature', models.BooleanField(default=False, help_text='Mark as a featured tour.')),
                ('new_arrival', models.BooleanField(default=False, help_text='Mark as a new arrival.')),
                ('clearance_sale', models.BooleanField(default=False, help_text='Mark as a clearance sale.')),
                ('active', models.BooleanField(default=True, help_text='Is the tour active?')),
                ('currency', models.ForeignKey(help_text='Currency for pricing.', on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='travel.currency')),
                ('category', models.ForeignKey(help_text='Category of the tour.', on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='travel.tourcategory')),
                ('tour_type', models.ForeignKey(help_text='Type of the tour.', on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='travel.tourtype')),
                ('type', models.ForeignKey(help_text='Tour type option.', on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='travel.tourtypeoption')),
            ],
        ),
    ]
