# Generated by Django 5.1.4 on 2024-12-11 16:24

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_t_class_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary', tinymce.models.HTMLField(help_text='Itinerary details in HTML format.')),
                ('includes', tinymce.models.HTMLField(help_text='What is included in the tour, in HTML format.')),
                ('excludes', tinymce.models.HTMLField(help_text='What is excluded from the tour, in HTML format.')),
                ('cancellation', tinymce.models.HTMLField(help_text='Cancellation policies in HTML format.')),
                ('notes', tinymce.models.HTMLField(help_text='Additional notes in HTML format.')),
                ('tour', models.OneToOneField(help_text='Related tour.', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='travel.tour')),
            ],
        ),
    ]
