# Generated by Django 5.1.4 on 2024-12-11 16:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_tourdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourdetail',
            name='cancellation',
            field=ckeditor.fields.RichTextField(help_text='Cancellation policies.'),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='excludes',
            field=ckeditor.fields.RichTextField(help_text='What is excluded from the tour.'),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='includes',
            field=ckeditor.fields.RichTextField(help_text='What is included in the tour.'),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='itinerary',
            field=ckeditor.fields.RichTextField(help_text='Itinerary details.'),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='notes',
            field=ckeditor.fields.RichTextField(help_text='Additional notes.'),
        ),
    ]
