# Generated by Django 5.1.4 on 2024-12-11 16:49

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_alter_tourdetail_cancellation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourdetail',
            name='cancellation',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='excludes',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='includes',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='itinerary',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='notes',
            field=tinymce.models.HTMLField(),
        ),
    ]
