# Generated by Django 5.1.4 on 2024-12-11 17:04

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_alter_tourdetail_cancellation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourdetail',
            name='cancellation',
        ),
        migrations.AddField(
            model_name='tourdetail',
            name='cancellation_policy',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='excludes',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='includes',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='itinerary',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='notes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
