# Generated by Django 5.1.4 on 2024-12-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_remove_tourdetail_cancellation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdetail',
            name='additional_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='cancellation_policy',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='excludes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='includes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='itinerary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
