# Generated by Django 5.1.4 on 2024-12-11 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_tourdetail_additional_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourdetail',
            name='additional_info',
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('tour_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='travel.tourdetail')),
            ],
        ),
    ]
