# Generated by Django 5.1.4 on 2024-12-12 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_remove_tourdetail_additional_info_customfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload tour photo.', upload_to='tour_photos/')),
                ('tour', models.ForeignKey(help_text='Related tour for the photo.', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='travel.tour')),
            ],
        ),
    ]
