# Generated by Django 5.1.4 on 2024-12-12 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_tourphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(help_text='Name of the country.', max_length=100)),
                ('state', models.CharField(help_text='Name of the state.', max_length=100)),
                ('num_of_days', models.PositiveIntegerField(help_text='Number of days spent in the city.')),
                ('num_of_nights', models.PositiveIntegerField(help_text='Number of nights spent in the city.')),
                ('tour', models.ForeignKey(help_text='Related tour.', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='travel.tour')),
            ],
        ),
    ]
