# Generated by Django 5.1.4 on 2024-12-12 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_country_remove_tourcity_country_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourtypeoption',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the tour type option.', null=True),
        ),
        migrations.AddField(
            model_name='tourtypeoption',
            name='is_fixed_departure',
            field=models.BooleanField(default=False, help_text='Indicates if this option is a Fixed Departure tour.'),
        ),
        migrations.AddField(
            model_name='tourtypeoption',
            name='is_tour_package',
            field=models.BooleanField(default=False, help_text='Indicates if this option is a Tour Package.'),
        ),
        migrations.AlterField(
            model_name='tourtypeoption',
            name='name',
            field=models.CharField(help_text='Type of the tour option (e.g., Fixed Departure or Tour Package).', max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_departure_date', models.DateField(blank=True, help_text='Date for Fixed Departures.', null=True)),
                ('from_date', models.DateField(blank=True, help_text='Start date for Tour Packages.', null=True)),
                ('to_date', models.DateField(blank=True, help_text='End date for Tour Packages.', null=True)),
                ('tour', models.ForeignKey(help_text='Related tour.', on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='travel.tour')),
            ],
        ),
    ]
