# Generated by Django 5.1.4 on 2024-12-12 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_tourtypeoption_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourvisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_country', models.CharField(help_text='Name of the Visa Country.', max_length=100)),
                ('tour', models.ForeignKey(help_text='Related tour.', on_delete=django.db.models.deletion.CASCADE, related_name='Visa', to='travel.tour')),
            ],
        ),
    ]
