# Generated by Django 5.1.4 on 2024-12-12 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_tourvisa'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the state.', max_length=100)),
                ('state', models.ForeignKey(help_text='Related country.', on_delete=django.db.models.deletion.CASCADE, related_name='city', to='travel.state')),
            ],
            options={
                'unique_together': {('name', 'state')},
            },
        ),
        migrations.CreateModel(
            name='TourHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(help_text='Name of the hotel.', max_length=255)),
                ('city', models.ForeignKey(help_text='T-class', on_delete=django.db.models.deletion.CASCADE, related_name='Hotel_city', to='travel.city')),
                ('destination', models.ForeignKey(help_text='T-class', on_delete=django.db.models.deletion.CASCADE, related_name='Hotel_destination', to='travel.state')),
                ('t_class', models.ForeignKey(help_text='T-class', on_delete=django.db.models.deletion.CASCADE, related_name='t_class_hotel', to='travel.t_class')),
                ('tour', models.ForeignKey(help_text='Related tour.', on_delete=django.db.models.deletion.CASCADE, related_name='tour_hotels', to='travel.tour')),
            ],
        ),
    ]
