# Generated by Django 5.1.4 on 2024-12-16 11:42

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_city_tourhotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourdetail',
            name='cancellation_policy',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='default'),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='excludes',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='default'),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='includes',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='default'),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='itinerary',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='default'),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='notes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='default'),
        ),
    ]
