# Generated by Django 5.1.4 on 2024-12-20 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0021_alter_tourdetail_cancellation_policy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('adult_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('twin_sharing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extra_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('validity_date_from', models.DateField()),
                ('validity_date_to', models.DateField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='travel.cart')),
                ('t_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.t_class')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.tour')),
            ],
        ),
    ]
