# Generated by Django 5.1.4 on 2024-12-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0024_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
