# Generated by Django 5.1.4 on 2024-12-21 14:00

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0025_inquiry_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='value',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='default'),
        ),
    ]
