# Generated by Django 5.1.4 on 2024-12-23 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0027_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('adult_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('twin_sharing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extra_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='travel.order')),
                ('t_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.t_class')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.tour')),
            ],
        ),
    ]
