# Generated by Django 5.1.4 on 2024-12-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0028_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
