# Generated by Django 5.1.4 on 2024-12-30 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0035_agent_chatrequest_chatmessage_problemrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inquery', to='travel.city'),
            preserve_default=False,
        ),
    ]
