# Generated by Django 5.1.4 on 2025-01-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0036_inquiry_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='city',
        ),
    ]
