# Generated by Django 5.1.4 on 2025-01-06 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0038_alter_tourcity_tour_alter_tourvisa_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourcity',
            name='tour',
            field=models.ForeignKey(help_text='Related tour.', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='travel.tour'),
        ),
        migrations.AlterField(
            model_name='tourvisa',
            name='tour',
            field=models.ForeignKey(help_text='Related tour.', on_delete=django.db.models.deletion.CASCADE, related_name='Visa', to='travel.tour'),
        ),
    ]
