# Generated by Django 5.1.4 on 2025-02-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0040_alter_country_name_alter_customfield_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourdetail',
            name='cancellation_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='excludes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='includes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='itinerary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
