# Generated by Django 5.1.4 on 2025-02-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0041_alter_tourdetail_cancellation_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
